- .gitignore
- source/includes/code-examples/quick-reference.cs
- source/quick-reference.txt
Jira - https://jira.mongodb.org/browse/DOCSP-32563
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/entity-framework/docsworker-xlarge/DOCSP-32563-quick-reference/quick-reference/
> Docsp 32563 quick reference

- config/redirects
Redirects file was missing v7.0
> Add v7 to redirects

- source/quick-start.txt
Staging: https://preview-mongodbmongokart.gatsbyjs.io/entity-framework/add-prerelease-flag/quick-start/#add-the-mongodb-entity-framework-provider-as-a-dependency
> add prerelease flag

- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-34125
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/ORM-fix/
> Change O/RM to ORM

- source/includes/compatibility-table.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-34254
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-34254-mongodb-compatibility/
- [N/A] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
> DOCSP-34254 Add MongoDB version compatibility

- source/fundamentals.txt
- source/fundamentals/query-data.txt
- source/includes/code-examples/quick-reference.cs
- source/query-data.txt
- source/quick-reference.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32165
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-32165-read-basics/fundamentals/query-data/
> DOCSP-32165 Query Data

- snooty.toml
- source/fundamentals.txt
- source/fundamentals/query-data.txt
- source/fundamentals/write-data.txt
- source/includes/code-examples/quick-reference.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-32166
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-32166-write-data/fundamentals/write-data/
> DOCSP-32166 - Write Basics

- source/fundamentals/configure.txt
- source/fundamentals/query-data.txt
- source/fundamentals/write-data.txt
- source/quick-reference.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32853
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-32853-fund-links/quick-reference/
> DOCSP-32853 Add fundamentals links to quick reference

- source/index.txt
- source/limitations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32179
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-32179-limitations/limitations/
> DOCSP-32179 - EF Limitations

- snooty.toml
- source/limitations.txt
Reorganizing Limitations page based on engineering feedback
JIRA - N/A
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/reorganize-limitations/limitations/
> Reorganize Limitations page

- source/faq.txt
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39419
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-39419-ef-csharp-compare/faq/#what-is-the-difference-between-the-.net-c--driver-and-the-entity-framework-core-provider-
> DOCSP-39419 Compare EF and Csharp driver 

- source/quick-start.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41820
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-41820-environment-variable-setting/quick-start/#add-your-connection-string-to-an-environment-variable
> DOCSP-41820 Fix code example not showing

- source/includes/quick-start/Program.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-42457>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/entity-framework/DOCSP-42457-PascalCase/quick-start/>
> DOCSP-42457: Use PascalCase for Movie class

- source/includes/quick-start/Program.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-42457>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/entity-framework/DOCSP-42457-PascalFollow/quick-start/>
> DOCSP-42457: PascalCase fast follow

- source/includes/code-examples/quick-reference.cs
- source/includes/fundamentals/code-examples/configure/ConfigureEFProvider.cs
- source/includes/quick-start/Program.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-42885>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/entity-framework/DOCSP-42885-public-classes/quick-start/>
> DOCSP-42885: Update Quick Start to use public classes

- source/fundamentals.txt
- source/fundamentals/optimistic-concurrency.txt
- source/includes/fundamentals/code-examples/DbContextConcurrency.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-42175
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/entity-framework/DOCSP-42175-optimistic-concurrency/fundamentals/optimistic-concurrency/
> DOCSP-42175 Concurrency Fundamentals

- source/fundamentals.txt
- source/index.txt
Reverts mongodb/docs-entity-framework#39
> Revert "DOCSP-44898 - Add TOC labels"

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-46109
> DOCSP-46109 - Add redirect versions

- snooty.toml
- source/fundamentals.txt
- source/fundamentals/indexes.txt
- source/includes/fundamentals/code-examples/indexes.cs
- source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45670
Staging - https://deploy-preview-49--docs-entity-framework.netlify.app/fundamentals/indexes/
> DOCSP-45670 Indexes guide

- source/faq.txt
- source/includes/code-examples/faq.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-36867
<li><a href=https://deploy-preview-57--docs-entity-framework.netlify.app/faq>faq</a></li>
> DOCSP-36867 Perform operations with driver

- source/fundamentals/query-data.txt
- source/includes/fundamentals/code-examples/aggregation.cs
- source/limitations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47510>
Staging - <https://deploy-preview-55--docs-entity-framework.netlify.app/fundamentals/query-data/#scalar-aggregations>
> DOCSP-47510 Add new aggregation operation examples
